
	// This struct holds all parameters possible for one tree:
 	struct ATREE {	char name [ 16 ];
  					int branches;
  					bool usehig;
  					bool glblscl;
  					bool sctrnsl;
  					bool usetwst;
					long double	radius;
					long double	height;
  	  	            long double	height0;
	      	        long double	scale0;
                    long double leanc0;
                    long double rotatec0;
                    long double leans0;
                    long double rotates0;
                  long double twistc0;
                  long double twists0;
                  long double height1;
                  long double scale1;
                  long double leanc1;
                  long double leans1;
                  long double rotatec1;
                  long double rotates1;
                  long double twistc1;
                  long double twists1;
                  long double height2;
                  long double scale2;
                  long double leanc2;
                  long double leans2;
                  long double rotatec2;
                  long double rotates2;
                  long double twistc2;
                  long double twists2;
                  long double height3;
                  long double scale3;
                  long double leanc3;
                  long double leans3;
                  long double rotatec3;
                  long double rotates3;
                  long double twistc3;
                  long double twists3;
                  long double height4;
                  long double scale4;
                  long double leanc4;
                  long double leans4;
                  long double rotatec4;
                  long double rotates4;
                  long double twistc4;
                  long double twists4;
                  long double height5;
                  long double scale5;
                  long double leanc5;
                  long double leans5;
                  long double rotatec5;
                  long double rotates5;
                  long double twistc5;
                  long double twists5;
                  long double height6;
                  long double scale6;
                  long double leanc6;
                  long double leans6;
                  long double rotatec6;
                  long double rotates6;
                  long double twistc6;
                  long double twists6;
                  long double height7;
                  long double scale7;
                  long double leanc7;
                  long double leans7;
                  long double rotatec7;
                  long double rotates7;
                  long double twistc7;
                  long double twists7;
  							};

